export default [
  {
    solutions: [
      {
        category: "COFFEE COUNTER ITEMS",
        words: ["CUP", " LID", " STIRRER", " STRAW"],
      },
      {
        category: "NOCTURNAL ANIMALS",
        words: ["BAT", " MOTH", " OWL", " WOLF"],
      },
      {
        category: "THINGS THAT ARE RED",
        words: ["BEET", " BRICK", " CARDINAL", " POPPY"],
      },
      {
        category: "___ FIGURE",
        words: ["ACTION", " BALLPARK", " GO", " STICK"],
      },
    ],
    allWords: [
      "CUP",
      " LID",
      " STIRRER",
      " STRAW",
      "BAT",
      " MOTH",
      " OWL",
      " WOLF",
      "BEET",
      " BRICK",
      " CARDINAL",
      " POPPY",
      "ACTION",
      " BALLPARK",
      " GO",
      " STICK",
    ],
  },
  {
    solutions: [
      {
        category: "PLAYING CARD SUITS",
        words: ["CLUB", " DIAMOND", " HEART", " SPADE"],
      },
      {
        category: "GOLF CLUBS",
        words: ["IRON", " PUTTER", " WEDGE", " WOOD"],
      },
      {
        category: "YEARN",
        words: ["ACHE", " LONG", " PINE", " THIRST"],
      },
      {
        category: "INSUFFICIENT",
        words: ["LOW", " SHORT", " SHY", " WANTING"],
      },
    ],
    allWords: [
      "CLUB",
      " DIAMOND",
      " HEART",
      " SPADE",
      "IRON",
      " PUTTER",
      " WEDGE",
      " WOOD",
      "ACHE",
      " LONG",
      " PINE",
      " THIRST",
      "LOW",
      " SHORT",
      " SHY",
      " WANTING",
    ],
  },
  {
    solutions: [
      {
        category: "VERY IMPORTANT",
        words: ["CENTRAL", " CRITICAL", " KEY", " VITAL"],
      },
      {
        category: "RECYCLNG CATEGORIES",
        words: ["GLASS", " METAL", " PAPER", " PLASTIC"],
      },
      {
        category: "HUDSONS",
        words: ["HENRY", " JENNIFER", " KATE", " ROCK"],
      },
      {
        category: "WHAT “BEAT” MAY MEAN",
        words: ["ASSIGNMENT", " DEFEAT", " TEMPO", " TIRED"],
      },
    ],
    allWords: [
      "CENTRAL",
      " CRITICAL",
      " KEY",
      " VITAL",
      "GLASS",
      " METAL",
      " PAPER",
      " PLASTIC",
      "HENRY",
      " JENNIFER",
      " KATE",
      " ROCK",
      "ASSIGNMENT",
      " DEFEAT",
      " TEMPO",
      " TIRED",
    ],
  },
  {
    solutions: [
      {
        category: "REFLECT LIGHT",
        words: ["FLASH", " GLEAM", " GLITTER", " SPARKLE"],
      },
      {
        category: "WAYS TO GATHER FOOD",
        words: ["FISH", " FORAGE", " HUNT", " TRAP"],
      },
      {
        category: "RAP SUBGENRES",
        words: ["BOUNCE", " CRUNK", " DRILL", " GRIME"],
      },
      {
        category: "LIGHT ___",
        words: ["BEER", " BULB", " RAIL", " YEAR"],
      },
    ],
    allWords: [
      "FLASH",
      " GLEAM",
      " GLITTER",
      " SPARKLE",
      "FISH",
      " FORAGE",
      " HUNT",
      " TRAP",
      "BOUNCE",
      " CRUNK",
      " DRILL",
      " GRIME",
      "BEER",
      " BULB",
      " RAIL",
      " YEAR",
    ],
  },
  {
    solutions: [
      {
        category: "PRODUCED BY TREES",
        words: ["ACORN", " CONE", " POLLEN", " SAP"],
      },
      {
        category: "CANDY STORE TREATS",
        words: ["CHOCOLATE", " GUM", " LICORICE", " LOLLIPOP"],
      },
      {
        category: "TARGET OF A SCHEME",
        words: ["CHUMP", " FOOL", " MARK", " SUCKER"],
      },
      {
        category: "THINGS WITH EYE(S)",
        words: ["FACE", " HURRICANE", " NEEDLE", " POTATO"],
      },
    ],
    allWords: [
      "ACORN",
      " CONE",
      " POLLEN",
      " SAP",
      "CHOCOLATE",
      " GUM",
      " LICORICE",
      " LOLLIPOP",
      "CHUMP",
      " FOOL",
      " MARK",
      " SUCKER",
      "FACE",
      " HURRICANE",
      " NEEDLE",
      " POTATO",
    ],
  },
  {
    solutions: [
      {
        category: "SNAKES",
        words: ["BOA", " MAMBA", " PYTHON", " VIPER"],
      },
      {
        category: "LINGERIE",
        words: ["GARTER", " SLIP", " TEDDY", " THONG"],
      },
      {
        category: "SUMMARY",
        words: ["ABSTRACT", " BRIEF", " DIGEST", " RUNDOWN"],
      },
      {
        category: "FULL ___",
        words: ["CIRCLE", " HOUSE", " MONTY", " MOON"],
      },
    ],
    allWords: [
      "BOA",
      " MAMBA",
      " PYTHON",
      " VIPER",
      "GARTER",
      " SLIP",
      " TEDDY",
      " THONG",
      "ABSTRACT",
      " BRIEF",
      " DIGEST",
      " RUNDOWN",
      "CIRCLE",
      " HOUSE",
      " MONTY",
      " MOON",
    ],
  },
  {
    solutions: [
      {
        category: "BRIDAL ACCESSORIES",
        words: ["BOUQUET", " RING", " TRAIN", " VEIL"],
      },
      {
        category: "“C” WORDS FOR “ENVELOP”",
        words: ["CAKE", " COAT", " COVER", " CRUST"],
      },
      {
        category: "JACKS",
        words: ["BLACK", " FROST", " MA", " SPARROW"],
      },
      {
        category: "SOCIAL MEDIA APP ENDINGS",
        words: ["BOOK", " GRAM", " IN", " TUBE"],
      },
    ],
    allWords: [
      "BOUQUET",
      " RING",
      " TRAIN",
      " VEIL",
      "CAKE",
      " COAT",
      " COVER",
      " CRUST",
      "BLACK",
      " FROST",
      " MA",
      " SPARROW",
      "BOOK",
      " GRAM",
      " IN",
      " TUBE",
    ],
  },
  {
    solutions: [
      {
        category: "KITCHEN UTENSILS",
        words: ["GRATER", " LADLE", " PEELER", " WHISK"],
      },
      {
        category: "VERTEBRATES",
        words: ["BIRD", " FISH", " MAMMAL", " REPTILE"],
      },
      {
        category: "SUPER MARIO-RELATED",
        words: ["DINOSAUR", " MUSHROOM", " PLUMBER", " PRINCESS"],
      },
      {
        category: "SITCOM FAMILIES",
        words: ["BUNKER", " CLEAVER", " PARTRIDGE", " TANNER"],
      },
    ],
    allWords: [
      "GRATER",
      " LADLE",
      " PEELER",
      " WHISK",
      "BIRD",
      " FISH",
      " MAMMAL",
      " REPTILE",
      "DINOSAUR",
      " MUSHROOM",
      " PLUMBER",
      " PRINCESS",
      "BUNKER",
      " CLEAVER",
      " PARTRIDGE",
      " TANNER",
    ],
  },
  {
    solutions: [
      {
        category: "ROBUST",
        words: ["FIT", " HEALTHY", " SOUND", " STRONG"],
      },
      {
        category: "DECLINE",
        words: ["DIP", " DROP", " FALL", " SINK"],
      },
      {
        category: "WATER SOURCES",
        words: ["FOUNTAIN", " SPRING", " TAP", " WELL"],
      },
      {
        category: "WOMEN SINGERS",
        words: ["KEYS", " NICKS", " SUMMER", " SWIFT"],
      },
    ],
    allWords: [
      "FIT",
      " HEALTHY",
      " SOUND",
      " STRONG",
      "DIP",
      " DROP",
      " FALL",
      " SINK",
      "FOUNTAIN",
      " SPRING",
      " TAP",
      " WELL",
      "KEYS",
      " NICKS",
      " SUMMER",
      " SWIFT",
    ],
  },
  {
    solutions: [
      {
        category: "SODA FOUNTAIN ORDERS",
        words: ["FLOAT", " MALT", " SHAKE", " SUNDAE"],
      },
      {
        category: "SET, AS PLANS",
        words: ["CONCRETE", " FIRM", " SOLID", " TANGIBLE"],
      },
      {
        category: "M. NIGHT SHYAMALAN MOVIES",
        words: ["GLASS", " OLD", " SIGNS", " SPLIT"],
      },
      {
        category: "___BOARD",
        words: ["DASH", " HOVER", " KEY", " STAR"],
      },
    ],
    allWords: [
      "FLOAT",
      " MALT",
      " SHAKE",
      " SUNDAE",
      "CONCRETE",
      " FIRM",
      " SOLID",
      " TANGIBLE",
      "GLASS",
      " OLD",
      " SIGNS",
      " SPLIT",
      "DASH",
      " HOVER",
      " KEY",
      " STAR",
    ],
  },
  {
    solutions: [
      {
        category: "RESTAURANT WORKERS",
        words: ["BARTENDER", " CHEF", " HOST", " SERVER"],
      },
      {
        category: "MOTOR VEHICLES",
        words: ["BUS", " CAR", " MOTORCYCLE", " TRUCK"],
      },
      {
        category: "MUPPETS",
        words: ["ANIMAL", " BEAKER", " GONZO", " SCOOTER"],
      },
      {
        category: "HAND- AND FOOT-RELATED SLANG",
        words: ["DIGIT", " DOG", " MITT", " PIGGY"],
      },
    ],
    allWords: [
      "BARTENDER",
      " CHEF",
      " HOST",
      " SERVER",
      "BUS",
      " CAR",
      " MOTORCYCLE",
      " TRUCK",
      "ANIMAL",
      " BEAKER",
      " GONZO",
      " SCOOTER",
      "DIGIT",
      " DOG",
      " MITT",
      " PIGGY",
    ],
  },
  {
    solutions: [
      {
        category: "REPLACEMENT",
        words: ["BACKUP", " COPY", " EXTRA", " SPARE"],
      },
      {
        category: "BOWLING",
        words: ["ALLEY", " BALL", " LANE", " PIN"],
      },
      {
        category: "COMMON MERCH ITEMS",
        words: ["MUG", " PEN", " TEE", " TOTE"],
      },
      {
        category: "NUMBER HOMOPHONES",
        words: ["ATE", " FOR", " TOO", " WON"],
      },
    ],
    allWords: [
      "BACKUP",
      " COPY",
      " EXTRA",
      " SPARE",
      "ALLEY",
      " BALL",
      " LANE",
      " PIN",
      "MUG",
      " PEN",
      " TEE",
      " TOTE",
      "ATE",
      " FOR",
      " TOO",
      " WON",
    ],
  },
  {
    solutions: [
      {
        category: "WEB BROWSER-RELATED",
        words: ["BOOKMARK", " HISTORY", " TAB", " WINDOW"],
      },
      {
        category: "SHIRT FEATURES",
        words: ["BUTTON", " COLLAR", " CUFF", " POCKET"],
      },
      {
        category: "CONNECTION",
        words: ["BOND", " LINK", " RELATION", " TIE"],
      },
      {
        category: "DIRTY ___",
        words: ["DOZEN", " JOKE", " LAUNDRY", " MARTINI"],
      },
    ],
    allWords: [
      "BOOKMARK",
      " HISTORY",
      " TAB",
      " WINDOW",
      "BUTTON",
      " COLLAR",
      " CUFF",
      " POCKET",
      "BOND",
      " LINK",
      " RELATION",
      " TIE",
      "DOZEN",
      " JOKE",
      " LAUNDRY",
      " MARTINI",
    ],
  },
  {
    solutions: [
      {
        category: "INTELLIGENT",
        words: ["BRIGHT", " CLEVER", " QUICK", " SHARP"],
      },
      {
        category: "AIRLINES",
        words: ["ALASKA", " FRONTIER", " SOUTHWEST", " SPIRIT"],
      },
      {
        category: "WESTERN TROPES",
        words: ["COWBOY", " DRIFTER", " OUTLAW", " SHERIFF"],
      },
      {
        category: "TV SHOW TITLE SURNAMES",
        words: ["LASSO", " MARS", " ROGERS", " SMART"],
      },
    ],
    allWords: [
      "BRIGHT",
      " CLEVER",
      " QUICK",
      " SHARP",
      "ALASKA",
      " FRONTIER",
      " SOUTHWEST",
      " SPIRIT",
      "COWBOY",
      " DRIFTER",
      " OUTLAW",
      " SHERIFF",
      "LASSO",
      " MARS",
      " ROGERS",
      " SMART",
    ],
  },
  {
    solutions: [
      {
        category: "FRUITS",
        words: ["APRICOT", " FIG", " GRAPE", " LIME"],
      },
      {
        category: "LUXURIOUS",
        words: ["DELUXE", " GRAND", " LAVISH", " OPULENT"],
      },
      {
        category: "BEST ACTRESS OSCAR WINNERS",
        words: ["BERRY", " FOSTER", " STONE", " SWANK"],
      },
      {
        category: "WHAT “GREEN” MIGHT MEAN",
        words: ["ENVIOUS", " FRESH", " NAIVE", " UNWELL"],
      },
    ],
    allWords: [
      "APRICOT",
      " FIG",
      " GRAPE",
      " LIME",
      "DELUXE",
      " GRAND",
      " LAVISH",
      " OPULENT",
      "BERRY",
      " FOSTER",
      " STONE",
      " SWANK",
      "ENVIOUS",
      " FRESH",
      " NAIVE",
      " UNWELL",
    ],
  },
  {
    solutions: [
      {
        category: "FAIRY TALE FIGURES",
        words: ["GIANT", " PRINCESS", " WITCH", " WOLF"],
      },
      {
        category: "CHESS TERMS",
        words: ["BISHOP", " MATE", " GAMBIT", " QUEEN"],
      },
      {
        category: "“PEANUTS” CHARACTERS",
        words: ["CHARLIE", " PEPPERMINT PATTY", " PIGPEN", " WOODSTOCK"],
      },
      {
        category: "I LOVE ___",
        words: ["LUCY", " NEW YORK", " ROCK 'N ROLL", " YOU"],
      },
    ],
    allWords: [
      "GIANT",
      " PRINCESS",
      " WITCH",
      " WOLF",
      "BISHOP",
      " MATE",
      " GAMBIT",
      " QUEEN",
      "CHARLIE",
      " PEPPERMINT PATTY",
      " PIGPEN",
      " WOODSTOCK",
      "LUCY",
      " NEW YORK",
      " ROCK 'N ROLL",
      " YOU",
    ],
  },
  {
    solutions: [
      {
        category: "BOVIDS",
        words: ["BUFFALO", " COW", " GOAT", " SHEEP"],
      },
      {
        category: "EMIT LIGHT",
        words: ["BEAM", " GLOW", " RADIATE", " SHINE"],
      },
      {
        category: "GYMNASTICS APPARATUS",
        words: ["FLOOR", " HORSE", " RINGS", " VAULT"],
      },
      {
        category: "WORDS THAT SOUND LIKE TWO LETTERS",
        words: ["CUTIE", " ENVY", " EXCEL", " SEEDY"],
      },
    ],
    allWords: [
      "BUFFALO",
      " COW",
      " GOAT",
      " SHEEP",
      "BEAM",
      " GLOW",
      " RADIATE",
      " SHINE",
      "FLOOR",
      " HORSE",
      " RINGS",
      " VAULT",
      "CUTIE",
      " ENVY",
      " EXCEL",
      " SEEDY",
    ],
  },
  {
    solutions: [
      {
        category: "EYE PARTS",
        words: ["IRIS", " LENS", " PUPIL", " RETINA"],
      },
      {
        category: "COUNTERFEIT",
        words: ["BOGUS", " FAKE", " PHONY", " SHAM"],
      },
      {
        category: "RADIO LINGO",
        words: ["COPY", " OUT", " OVER", " ROGER"],
      },
      {
        category: "SONGS THAT ARE NAMES",
        words: ["ALEJANDRO", " LOLA", " MICHELLE", " STAN"],
      },
    ],
    allWords: [
      "IRIS",
      " LENS",
      " PUPIL",
      " RETINA",
      "BOGUS",
      " FAKE",
      " PHONY",
      " SHAM",
      "COPY",
      " OUT",
      " OVER",
      " ROGER",
      "ALEJANDRO",
      " LOLA",
      " MICHELLE",
      " STAN",
    ],
  },
  {
    solutions: [
      {
        category: "“SKEDADDLE!”",
        words: ["GET OUT", " GO", " LEAVE", " SCRAM"],
      },
      {
        category: "PRONOUNS",
        words: ["ME", " THEM", " US", " YOU"],
      },
      {
        category: "ANAGRAMS",
        words: ["NOPE", " OPEN", " PEON", " PONE"],
      },
      {
        category: "___ BABY",
        words: ["BEANIE", " FUR", " NEPO", " SANTA"],
      },
    ],
    allWords: [
      "GET OUT",
      " GO",
      " LEAVE",
      " SCRAM",
      "ME",
      " THEM",
      " US",
      " YOU",
      "NOPE",
      " OPEN",
      " PEON",
      " PONE",
      "BEANIE",
      " FUR",
      " NEPO",
      " SANTA",
    ],
  },
  {
    solutions: [
      {
        category: "HOT DRINKS",
        words: ["CHAI", " COCOA", " COFFEE", " TEA"],
      },
      {
        category: "ANIMAL SOUNDS",
        words: ["BUZZ", " CLUCK", " MEOW", " OINK"],
      },
      {
        category: "TREE FEATURES",
        words: ["BARK", " BRANCH", " ROOT", " TRUNK"],
      },
      {
        category: "INSIDE INFO",
        words: ["DIRT", " DISH", " SCOOP", " SKINNY"],
      },
    ],
    allWords: [
      "CHAI",
      " COCOA",
      " COFFEE",
      " TEA",
      "BUZZ",
      " CLUCK",
      " MEOW",
      " OINK",
      "BARK",
      " BRANCH",
      " ROOT",
      " TRUNK",
      "DIRT",
      " DISH",
      " SCOOP",
      " SKINNY",
    ],
  },
  {
    solutions: [
      {
        category: "HALLOWEEN DECORATIONS",
        words: ["BAT", " COBWEB", " PUMPKIN", " TOMBSTONE"],
      },
      {
        category: "TV SHOWS",
        words: ["24", " BONES", " FIREFLY", " WEEDS"],
      },
      {
        category: "SLOT MACHINE SYMBOLS",
        words: ["7", " BAR", " BELL", " CHERRY"],
      },
      {
        category: "NUMBERS IN BOOK TITLES",
        words: ["22, 451", " 2001", " 20", "000"],
      },
    ],
    allWords: [
      "BAT",
      " COBWEB",
      " PUMPKIN",
      " TOMBSTONE",
      "24",
      " BONES",
      " FIREFLY",
      " WEEDS",
      "7",
      " BAR",
      " BELL",
      " CHERRY",
      "22, 451",
      " 2001",
      " 20",
      "000",
    ],
  },
  {
    solutions: [
      {
        category: "AMAZON ANIMALS",
        words: ["ANACONDA", " CAPYBARA", " JAGUAR", " TOUCAN"],
      },
      {
        category: "LOWEST POINT",
        words: ["BASE", " BOTTOM", " FOOT", " FOUNDATION"],
      },
      {
        category: "MUSICALS",
        words: ["COMPANY", " GREASE", " HAIR", " RENT"],
      },
      {
        category: "SEA ___",
        words: ["CHANGE", " CUCUMBER", " LEGS", " LION"],
      },
    ],
    allWords: [
      "ANACONDA",
      " CAPYBARA",
      " JAGUAR",
      " TOUCAN",
      "BASE",
      " BOTTOM",
      " FOOT",
      " FOUNDATION",
      "COMPANY",
      " GREASE",
      " HAIR",
      " RENT",
      "CHANGE",
      " CUCUMBER",
      " LEGS",
      " LION",
    ],
  },
  {
    solutions: [
      {
        category: "BASEBALL CALLS",
        words: ["BALL", " OUT", " SAFE", " STRIKE"],
      },
      {
        category: "HEAT SOURCES",
        words: ["FORGE", " FURNACE", " KILN", " OVEN"],
      },
      {
        category: "FISH THAT ARE VERBS",
        words: ["CARP", " CATFISH", " FLOUNDER", " SMELT"],
      },
      {
        category: "SILENT “L”",
        words: ["COLONEL", " SALMON", " WALK", " YOLK"],
      },
    ],
    allWords: [
      "BALL",
      " OUT",
      " SAFE",
      " STRIKE",
      "FORGE",
      " FURNACE",
      " KILN",
      " OVEN",
      "CARP",
      " CATFISH",
      " FLOUNDER",
      " SMELT",
      "COLONEL",
      " SALMON",
      " WALK",
      " YOLK",
    ],
  },
  {
    solutions: [
      {
        category: "INHERENT NATURE",
        words: ["ESSENCE", " HEART", " SPIRIT", " SOUL"],
      },
      {
        category: "FERMENETED ALCOHOLIC BEVERAGES",
        words: ["CIDER", " PORT", " SAKE", " STOUT"],
      },
      {
        category: "PIXAR MOVIES",
        words: ["BRAVE", " CARS", " COCO", " UP"],
      },
      {
        category: "___ TAPE",
        words: ["DEMO", " RED", " SCOTCH", " TICKER"],
      },
    ],
    allWords: [
      "ESSENCE",
      " HEART",
      " SPIRIT",
      " SOUL",
      "CIDER",
      " PORT",
      " SAKE",
      " STOUT",
      "BRAVE",
      " CARS",
      " COCO",
      " UP",
      "DEMO",
      " RED",
      " SCOTCH",
      " TICKER",
    ],
  },
  {
    solutions: [
      {
        category: "ROCKY HORROR PICTURE SHOW",
        words: ["HORROR", " PICTURE", " ROCKY", " SHOW"],
      },
      {
        category: "WHO FRAMED ROGER RABBIT",
        words: ["FRAMED", " RABBIT", " ROGER", " WHO"],
      },
      {
        category: "WHEN HARRY MET SALLY",
        words: ["HARRY", " MET", " SALLY", " WHEN"],
      },
      {
        category: "MAD MAX FURY ROAD",
        words: ["FURY", " MAD", " MAX", " ROAD"],
      },
    ],
    allWords: [
      "HORROR",
      " PICTURE",
      " ROCKY",
      " SHOW",
      "FRAMED",
      " RABBIT",
      " ROGER",
      " WHO",
      "HARRY",
      " MET",
      " SALLY",
      " WHEN",
      "FURY",
      " MAD",
      " MAX",
      " ROAD",
    ],
  },
  {
    solutions: [
      {
        category: "CREATURES IN FOLKLORE",
        words: ["GNOME", " GOBLIN", " OGRE", " TROLL"],
      },
      {
        category: "FLOWER PARTS",
        words: ["BUD", " LEAF", " PETAL", " STALK"],
      },
      {
        category: "ONE INVOLVED IN ESPIONAGE",
        words: ["AGENT", " MOLE", " PLANT", " SPY"],
      },
      {
        category: "CHINESE ZODIAC ANIMALS",
        words: ["DRAGON", " HORSE", " RABBIT", " TIGER"],
      },
    ],
    allWords: [
      "GNOME",
      " GOBLIN",
      " OGRE",
      " TROLL",
      "BUD",
      " LEAF",
      " PETAL",
      " STALK",
      "AGENT",
      " MOLE",
      " PLANT",
      " SPY",
      "DRAGON",
      " HORSE",
      " RABBIT",
      " TIGER",
    ],
  },
  {
    solutions: [
      {
        category: "INFORMATION DISPLAYS",
        words: ["CHART", " DIAGRAM", " GRAPH", " MAP"],
      },
      {
        category: "ADDITIONAL BENEFIT",
        words: ["BONUS", " EXTRA", " ICING", " PERK"],
      },
      {
        category: "THANKSGIVING FOOD",
        words: ["GRAVY", " PIE", " STUFFING", " TURKEY"],
      },
      {
        category: "SONG TITLES WITH PARENTHESES",
        words: ["I RAN", " ISTANBUL", " MONTERO", " SATISFACTION"],
      },
    ],
    allWords: [
      "CHART",
      " DIAGRAM",
      " GRAPH",
      " MAP",
      "BONUS",
      " EXTRA",
      " ICING",
      " PERK",
      "GRAVY",
      " PIE",
      " STUFFING",
      " TURKEY",
      "I RAN",
      " ISTANBUL",
      " MONTERO",
      " SATISFACTION",
    ],
  },
  {
    solutions: [
      {
        category: "PAINTING ACCESSORIES",
        words: ["BRUSH", " CANVAS", " EASEL", " PALETTE"],
      },
      {
        category: "AUTOMATIC TRANSMISSION SETTINGS",
        words: ["DRIVE", " NEUTRAL", " PARK", " REVERSE"],
      },
      {
        category: "THINGS WITH TEETH",
        words: ["COMB", " GEAR", " SAW", " ZIPPER"],
      },
      {
        category: "___ CHAIR",
        words: ["FIRST", " FOLDING", " HIGH", " LAWN"],
      },
    ],
    allWords: [
      "BRUSH",
      " CANVAS",
      " EASEL",
      " PALETTE",
      "DRIVE",
      " NEUTRAL",
      " PARK",
      " REVERSE",
      "COMB",
      " GEAR",
      " SAW",
      " ZIPPER",
      "FIRST",
      " FOLDING",
      " HIGH",
      " LAWN",
    ],
  },
  {
    solutions: [
      {
        category: "FEMALE ANIMALS",
        words: ["COW", " DOE", " HEN", " MARE"],
      },
      {
        category: "PRONOUNS",
        words: ["I", " IT", " THEY", " WE"],
      },
      {
        category: "ROMAN NUMERALS",
        words: ["D", " L", " M", " V"],
      },
      {
        category: "HOMOPHONES",
        words: ["EWE", " U", " YEW", " YOU"],
      },
    ],
    allWords: [
      "COW",
      " DOE",
      " HEN",
      " MARE",
      "I",
      " IT",
      " THEY",
      " WE",
      "D",
      " L",
      " M",
      " V",
      "EWE",
      " U",
      " YEW",
      " YOU",
    ],
  },
  {
    solutions: [
      {
        category: "AU NATUREL",
        words: ["BARE", " NAKED", " NUDE", " UNCLAD"],
      },
      {
        category: "BAKED GOODS",
        words: ["BUN", " DANISH", " MUFFIN", " TURNOVER"],
      },
      {
        category: "AMERICAN FOOTBALL ACTIONS",
        words: ["FUMBLE", " PUNT", " SACK", " SNAP"],
      },
      {
        category: "MANICURE STEPS",
        words: ["BUFF", " CLIP", " FILE", " POLISH"],
      },
    ],
    allWords: [
      "BARE",
      " NAKED",
      " NUDE",
      " UNCLAD",
      "BUN",
      " DANISH",
      " MUFFIN",
      " TURNOVER",
      "FUMBLE",
      " PUNT",
      " SACK",
      " SNAP",
      "BUFF",
      " CLIP",
      " FILE",
      " POLISH",
    ],
  },
  {
    solutions: [
      {
        category: "DRINK VESSELS",
        words: ["GOBLET", " SNIFTER", " TUMBLER", " STEIN"],
      },
      {
        category: "WOODWINDS",
        words: ["CLARINET", " FLUTE", " OBOE", " SAXOPHONE"],
      },
      {
        category: "AMERICAN POETS",
        words: ["BISHOP", " FROST", " OLDS", " POUND"],
      },
      {
        category: "CONSECUTIVE DOUBLE LETTERS",
        words: ["BALLOON", " BASSOON", " COFFEE", " FRICASSEE"],
      },
    ],
    allWords: [
      "GOBLET",
      " SNIFTER",
      " TUMBLER",
      " STEIN",
      "CLARINET",
      " FLUTE",
      " OBOE",
      " SAXOPHONE",
      "BISHOP",
      " FROST",
      " OLDS",
      " POUND",
      "BALLOON",
      " BASSOON",
      " COFFEE",
      " FRICASSEE",
    ],
  },
  {
    solutions: [
      {
        category: "APPETIZER UNIT",
        words: ["FRY", " NACHO", " POPPER", " WING"],
      },
      {
        category: "RESPONSE TO A CORRECT ANSWER",
        words: ["BINGO", " CORRECT", " RIGHT", " YES"],
      },
      {
        category: "MAR",
        words: ["CHIP", " DING", " NICK", " SCRATCH"],
      },
      {
        category: "___JACK",
        words: ["APPLE", " CRACKER", " FLAP", " LUMBER"],
      },
    ],
    allWords: [
      "FRY",
      " NACHO",
      " POPPER",
      " WING",
      "BINGO",
      " CORRECT",
      " RIGHT",
      " YES",
      "CHIP",
      " DING",
      " NICK",
      " SCRATCH",
      "APPLE",
      " CRACKER",
      " FLAP",
      " LUMBER",
    ],
  },
  {
    solutions: [
      {
        category: "PLAYGROUND FIXTURES",
        words: ["SANDBOX", " SEESAW", " SLIDE", " SWING"],
      },
      {
        category: "INFLUENCE",
        words: ["CLOUT", " PULL", " SWAY", " WEIGHT"],
      },
      {
        category: "EGYPTIAN SYMBOLS",
        words: ["ANKH", " CROOK", " EYE", " SCARAB"],
      },
      {
        category: "FONTS",
        words: ["COURIER", " IMPACT", " PAPYRUS", " TIMES"],
      },
    ],
    allWords: [
      "SANDBOX",
      " SEESAW",
      " SLIDE",
      " SWING",
      "CLOUT",
      " PULL",
      " SWAY",
      " WEIGHT",
      "ANKH",
      " CROOK",
      " EYE",
      " SCARAB",
      "COURIER",
      " IMPACT",
      " PAPYRUS",
      " TIMES",
    ],
  },
  {
    solutions: [
      {
        category: "DEPART QUICKLY",
        words: ["BOOK", " BOUNCE", " RUN", " SPLIT"],
      },
      {
        category: "ANIMALS THAT END WITH X",
        words: ["FOX", " IBEX", " LYNX", " ORYX"],
      },
      {
        category: "SHADES OF BLACK",
        words: ["EBONY", " JET", " ONYX", " RAVEN"],
      },
      {
        category: "WORDS BEFORE DAYS OF THE WEEK",
        words: ["ASH", " BLACK", " CYBER", " FAT"],
      },
    ],
    allWords: [
      "BOOK",
      " BOUNCE",
      " RUN",
      " SPLIT",
      "FOX",
      " IBEX",
      " LYNX",
      " ORYX",
      "EBONY",
      " JET",
      " ONYX",
      " RAVEN",
      "ASH",
      " BLACK",
      " CYBER",
      " FAT",
    ],
  },
  {
    solutions: [
      {
        category: "STATES OF ELATION",
        words: ["BLISS", " CLOUD NINE", " HEAVEN", " PARADISE"],
      },
      {
        category: "SCAM",
        words: ["CON", " FAST ONE", " HUSTLE", " RACKET"],
      },
      {
        category: "GREETING GESTURES",
        words: ["HIGH FIVE", " HUG", " SHAKE", " WAVE"],
      },
      {
        category: "___ LIST",
        words: ["BUCKET", " GUEST", " TOP TEN", " WISH"],
      },
    ],
    allWords: [
      "BLISS",
      " CLOUD NINE",
      " HEAVEN",
      " PARADISE",
      "CON",
      " FAST ONE",
      " HUSTLE",
      " RACKET",
      "HIGH FIVE",
      " HUG",
      " SHAKE",
      " WAVE",
      "BUCKET",
      " GUEST",
      " TOP TEN",
      " WISH",
    ],
  },
  {
    solutions: [
      {
        category: "POULTRY CUTS",
        words: ["BREAST", " DRUMSTICK", " TENDER", " WING"],
      },
      {
        category: "GOLF TERMS",
        words: ["DRIVER", " EAGLE", " HOLE", " STROKE"],
      },
      {
        category: "DRUM SET COMPONENTS",
        words: ["CYMBAL", " KICK", " SNARE", " TOM"],
      },
      {
        category: 'ASSOCIATED WITH "CRAWL"',
        words: ["INFANT", " PUB", " SWIMMING", " TICKER"],
      },
    ],
    allWords: [
      "BREAST",
      " DRUMSTICK",
      " TENDER",
      " WING",
      "DRIVER",
      " EAGLE",
      " HOLE",
      " STROKE",
      "CYMBAL",
      " KICK",
      " SNARE",
      " TOM",
      "INFANT",
      " PUB",
      " SWIMMING",
      " TICKER",
    ],
  },
  {
    solutions: [
      {
        category: "BOARD GAMES",
        words: ["RISK", " SORRY", " TABOO", " TROUBLE"],
      },
      {
        category: "NEWSPAPER SECTIONS",
        words: ["BUSINESS", " NATIONAL", " OPINION", " STYLE"],
      },
      {
        category: "FIGURES IN GREEK MYTH",
        words: ["ATLAS", " HERMES", " NIKE", " PARIS"],
      },
      {
        category: "ADJECTIVES IN RAPPERS' NAMES",
        words: ["FOXY", " GUCCI", " KILLER", " NOTORIOUS"],
      },
    ],
    allWords: [
      "RISK",
      " SORRY",
      " TABOO",
      " TROUBLE",
      "BUSINESS",
      " NATIONAL",
      " OPINION",
      " STYLE",
      "ATLAS",
      " HERMES",
      " NIKE",
      " PARIS",
      "FOXY",
      " GUCCI",
      " KILLER",
      " NOTORIOUS",
    ],
  },
  {
    solutions: [
      {
        category: "SOCIAL GATHERING",
        words: ["BASH", " BLOWOUT", " PARTY", " SHINDIG"],
      },
      {
        category: '"PINOCCHIO" FIGURES',
        words: ["CRICKET", " PUPPET", " WHALE", " WOODCARVER"],
      },
      {
        category: "FOUND IN A KITCHEN",
        words: ["COUNTER", " MIXER", " RANGE", " SINK"],
      },
      {
        category: "EASTER ___",
        words: ["BUNNY", " EGG", " ISLAND", " SUNDAY"],
      },
    ],
    allWords: [
      "BASH",
      " BLOWOUT",
      " PARTY",
      " SHINDIG",
      "CRICKET",
      " PUPPET",
      " WHALE",
      " WOODCARVER",
      "COUNTER",
      " MIXER",
      " RANGE",
      " SINK",
      "BUNNY",
      " EGG",
      " ISLAND",
      " SUNDAY",
    ],
  },
  {
    solutions: [
      {
        category: "EXTINCT ANIMALS",
        words: ["DODO", " MAMMOTH", " MASTODON", " TRILOBITE"],
      },
      {
        category: "FAILURES",
        words: ["BUSTS", " FLOPS", " MISSES", " TURKEYS"],
      },
      {
        category: "SLANG FOR CLOTHES",
        words: ["DUDS", " GETUP", " OUTFIT", " THREADS"],
      },
      {
        category: "KISS",
        words: ["PECK", " SMACK", " SMOOCH", " X"],
      },
    ],
    allWords: [
      "DODO",
      " MAMMOTH",
      " MASTODON",
      " TRILOBITE",
      "BUSTS",
      " FLOPS",
      " MISSES",
      " TURKEYS",
      "DUDS",
      " GETUP",
      " OUTFIT",
      " THREADS",
      "PECK",
      " SMACK",
      " SMOOCH",
      " X",
    ],
  },
  {
    solutions: [
      {
        category: "FACIAL HAIR",
        words: ["BEARD", " GOATEE", " MUSTACHE", " STUBBLE"],
      },
      {
        category: "BIKE PARTS",
        words: ["GEAR", " HANDLEBAR", " PEDAL", " WHEEL"],
      },
      {
        category: "PURSUE",
        words: ["DOG", " FOLLOW", " TAIL", " TRACK"],
      },
      {
        category: "THINGS THAT ARE CAST",
        words: ["DOUBT", " MOVIE", " SHADOW", " VOTE"],
      },
    ],
    allWords: [
      "BEARD",
      " GOATEE",
      " MUSTACHE",
      " STUBBLE",
      "GEAR",
      " HANDLEBAR",
      " PEDAL",
      " WHEEL",
      "DOG",
      " FOLLOW",
      " TAIL",
      " TRACK",
      "DOUBT",
      " MOVIE",
      " SHADOW",
      " VOTE",
    ],
  },
  {
    solutions: [
      {
        category: "PERFORMING ARTISTS",
        words: ["ACTOR", " DANCER", " SINGER", " STAND-UP"],
      },
      {
        category: "SANTA'S REINDEER",
        words: ["COMET", " CUPID", " DASHER", " VIXEN"],
      },
      {
        category: "SEEN ON VALENTINE'S DAY",
        words: ["CARD", " CHOCOLATE", " HEART", " ROSE"],
      },
      {
        category: '"BAD ___" MOVIES"',
        words: ["BOYS", " LIEUTENANT", " SANTA", " TASTE"],
      },
    ],
    allWords: [
      "ACTOR",
      " DANCER",
      " SINGER",
      " STAND-UP",
      "COMET",
      " CUPID",
      " DASHER",
      " VIXEN",
      "CARD",
      " CHOCOLATE",
      " HEART",
      " ROSE",
      "BOYS",
      " LIEUTENANT",
      " SANTA",
      " TASTE",
    ],
  },
  {
    solutions: [
      {
        category: "U.S. MOUNTAIN STATES",
        words: ["ARIZONA", " COLORADO", " NEVADA", " UTAH"],
      },
      {
        category: "SODA BRANDS",
        words: ["CRUSH", " MUG", " SPRITE", " SQUIRT"],
      },
      {
        category: "CLASSIC ROCK BANDS",
        words: ["GENESIS", " KANSAS", " RUSH", " YES"],
      },
      {
        category: "TONY ___",
        words: ["HAWK", " MONTANA", " SOPRANO", " STARK"],
      },
    ],
    allWords: [
      "ARIZONA",
      " COLORADO",
      " NEVADA",
      " UTAH",
      "CRUSH",
      " MUG",
      " SPRITE",
      " SQUIRT",
      "GENESIS",
      " KANSAS",
      " RUSH",
      " YES",
      "HAWK",
      " MONTANA",
      " SOPRANO",
      " STARK",
    ],
  },
  {
    solutions: [
      {
        category: "CAMPING SUPPLIES",
        words: ["COOLER", " LANTERN", " SLEEPING BAG", " TENT"],
      },
      {
        category: "INSULT",
        words: ["BARB", " DIG", " DISS", " JAB"],
      },
      {
        category: "TINY",
        words: ["MINUTE", " SLIGHT", " SMALL", " WEE"],
      },
      {
        category: "HAPPY ___",
        words: ["CAMPER", " HOUR", " MEAL", " MEDIUM"],
      },
    ],
    allWords: [
      "COOLER",
      " LANTERN",
      " SLEEPING BAG",
      " TENT",
      "BARB",
      " DIG",
      " DISS",
      " JAB",
      "MINUTE",
      " SLIGHT",
      " SMALL",
      " WEE",
      "CAMPER",
      " HOUR",
      " MEAL",
      " MEDIUM",
    ],
  },
  {
    solutions: [
      {
        category: "FRIEND",
        words: ["BUD", " CHUM", " MATE", " PAL"],
      },
      {
        category: "COOKWEAR",
        words: ["CROCK", " POT", " SKILLET", " WOK"],
      },
      {
        category: "SHOES",
        words: ["CLOG", " PUMP", " SLIDE", " WEDGE"],
      },
      {
        category: "SLANG FOR CANNABIS",
        words: ["GRASS", " HERB", " MARY JANE", " WEED"],
      },
    ],
    allWords: [
      "BUD",
      " CHUM",
      " MATE",
      " PAL",
      "CROCK",
      " POT",
      " SKILLET",
      " WOK",
      "CLOG",
      " PUMP",
      " SLIDE",
      " WEDGE",
      "GRASS",
      " HERB",
      " MARY JANE",
      " WEED",
    ],
  },
  {
    solutions: [
      {
        category: "UNITS OF VOLUME",
        words: ["CUP", " GALLON", " PINT", " QUART"],
      },
      {
        category: "EXTREMELY",
        words: ["AWFUL", " QUITE", " SUPER", " VERY"],
      },
      {
        category: "WORLD CURRENCIES",
        words: ["RAND", " REAL", " STERLING", " WON"],
      },
      {
        category: "___ CAKE",
        words: ["CARROT", " COFFEE", " POUND", " SPONGE"],
      },
    ],
    allWords: [
      "CUP",
      " GALLON",
      " PINT",
      " QUART",
      "AWFUL",
      " QUITE",
      " SUPER",
      " VERY",
      "RAND",
      " REAL",
      " STERLING",
      " WON",
      "CARROT",
      " COFFEE",
      " POUND",
      " SPONGE",
    ],
  },
  {
    solutions: [
      {
        category: "DESSERTS",
        words: ["CAKE", " COBBLER", " PIE", " TART"],
      },
      {
        category: "OCCUPATIONAL SURNAMES",
        words: ["FISHER", " MASON", " MILLER", " SMITH"],
      },
      {
        category: "ALTER DECEPTIVELY",
        words: ["DISTORT", " DOCTOR", " FUDGE", " TWIST"],
      },
      {
        category: "SQUARE ___",
        words: ["DANCE", " MEAL", " ONE", " ROOT"],
      },
    ],
    allWords: [
      "CAKE",
      " COBBLER",
      " PIE",
      " TART",
      "FISHER",
      " MASON",
      " MILLER",
      " SMITH",
      "DISTORT",
      " DOCTOR",
      " FUDGE",
      " TWIST",
      "DANCE",
      " MEAL",
      " ONE",
      " ROOT",
    ],
  },
  {
    solutions: [
      {
        category: "TIME PERIODS",
        words: ["CENTURY", " DECADE", " MILLENNIUM", " YEAR"],
      },
      {
        category: "BREAKFAST FOODS",
        words: ["CEREAL", " OMELET", " PANCAKE", " WAFFLE"],
      },
      {
        category: "PAINTERS",
        words: ["BACON", " CLOSE", " MUNCH", " WHISTLER"],
      },
      {
        category: "ONE IN A DOZEN",
        words: ["EGG", " JUROR", " MONTH", " ROSE"],
      },
    ],
    allWords: [
      "CENTURY",
      " DECADE",
      " MILLENNIUM",
      " YEAR",
      "CEREAL",
      " OMELET",
      " PANCAKE",
      " WAFFLE",
      "BACON",
      " CLOSE",
      " MUNCH",
      " WHISTLER",
      "EGG",
      " JUROR",
      " MONTH",
      " ROSE",
    ],
  },
  {
    solutions: [
      {
        category: "STATES OF MATTER",
        words: ["GAS", " LIQUID", " PLASMA", " SOLID"],
      },
      {
        category: "ENERGY",
        words: ["JUICE", " SPIRIT", " STEAM", " VIGOR"],
      },
      {
        category: "CLASSICAL ELEMENTS",
        words: ["AIR", " EARTH", " FIRE", " WATER"],
      },
      {
        category: "THINGS WITH RINGS",
        words: ["CIRCUS", " SATURN", " TREE", " WEDDING"],
      },
    ],
    allWords: [
      "GAS",
      " LIQUID",
      " PLASMA",
      " SOLID",
      "JUICE",
      " SPIRIT",
      " STEAM",
      " VIGOR",
      "AIR",
      " EARTH",
      " FIRE",
      " WATER",
      "CIRCUS",
      " SATURN",
      " TREE",
      " WEDDING",
    ],
  },
  {
    solutions: [
      {
        category: "CLASSIC DOG NAMES",
        words: ["FIDO", " LUCKY", " ROVER", " SPOT"],
      },
      {
        category: "PERCEIVE",
        words: ["CATCH", " NOTICE", " OBSERVE", " SEE"],
      },
      {
        category: "FISHING TERMS",
        words: ["BAIT", " CHUM", " FLY", " SINKER"],
      },
      {
        category: "T-___",
        words: ["BONE", " REX", " SHIRT", " STORM"],
      },
    ],
    allWords: [
      "FIDO",
      " LUCKY",
      " ROVER",
      " SPOT",
      "CATCH",
      " NOTICE",
      " OBSERVE",
      " SEE",
      "BAIT",
      " CHUM",
      " FLY",
      " SINKER",
      "BONE",
      " REX",
      " SHIRT",
      " STORM",
    ],
  },
  {
    solutions: [
      {
        category: "FASTENING VERBS",
        words: ["BUCKLE", " BUTTON", " SNAP", " ZIP"],
      },
      {
        category: "SLANG FOR ZERO",
        words: ["JACK", " NADA", " NOTHING", " SQUAT"],
      },
      {
        category: "GYM EXERCISES",
        words: ["CURL", " LUNGE", " PLANK", " PRESS"],
      },
      {
        category: '"CAPTAINS"',
        words: ["CRUNCH", " KANGAROO", " OBVIOUS", " PLANET"],
      },
    ],
    allWords: [
      "BUCKLE",
      " BUTTON",
      " SNAP",
      " ZIP",
      "JACK",
      " NADA",
      " NOTHING",
      " SQUAT",
      "CURL",
      " LUNGE",
      " PLANK",
      " PRESS",
      "CRUNCH",
      " KANGAROO",
      " OBVIOUS",
      " PLANET",
    ],
  },
  {
    solutions: [
      {
        category: "STATE ABBREVIATIONS",
        words: ["CO", " MA", " ME", " PA"],
      },
      {
        category: "MUSICAL NOTES",
        words: ["DO", " FA", " LA", " TI"],
      },
      {
        category: "GREEK LETTERS",
        words: ["MU", " NU", " PI", " XI"],
      },
      {
        category: "PERIODIC TABLE SYMBOLS",
        words: ["FE", " HE", " NA", " NI"],
      },
    ],
    allWords: [
      "CO",
      " MA",
      " ME",
      " PA",
      "DO",
      " FA",
      " LA",
      " TI",
      "MU",
      " NU",
      " PI",
      " XI",
      "FE",
      " HE",
      " NA",
      " NI",
    ],
  },
  {
    solutions: [
      {
        category: "THEORETICAL PHYSICISTS",
        words: ["EINSTEIN", " FEYNMAN", " HAWKING", " OPPENHEIMER"],
      },
      {
        category: "TALENT",
        words: ["FACULTY", " FLAIR", " GENIUS", " GIFT"],
      },
      {
        category: "AUSTRALIAN TERMS",
        words: ["BARBIE", " BUSH", " CRIKEY", " MATE"],
      },
      {
        category: "___ POINT",
        words: ["MATCH", " MOOT", " SELLING", " WEST"],
      },
    ],
    allWords: [
      "EINSTEIN",
      " FEYNMAN",
      " HAWKING",
      " OPPENHEIMER",
      "FACULTY",
      " FLAIR",
      " GENIUS",
      " GIFT",
      "BARBIE",
      " BUSH",
      " CRIKEY",
      " MATE",
      "MATCH",
      " MOOT",
      " SELLING",
      " WEST",
    ],
  },
  {
    solutions: [
      {
        category: "HORROR FRANCHISES",
        words: ["PURGE", " RING", " SAW", " SCREAM"],
      },
      {
        category: "SPORTS VENUES",
        words: ["COURT", " DIAMOND", " FIELD", " RINK"],
      },
      {
        category: "MAKE HAPPY",
        words: ["CHARM", " DELIGHT", " PLEASE", " TICKLE"],
      },
      {
        category: "JEWELRY",
        words: ["ANKLET", " BANGLE", " BROOCH", " PENDANT"],
      },
    ],
    allWords: [
      "PURGE",
      " RING",
      " SAW",
      " SCREAM",
      "COURT",
      " DIAMOND",
      " FIELD",
      " RINK",
      "CHARM",
      " DELIGHT",
      " PLEASE",
      " TICKLE",
      "ANKLET",
      " BANGLE",
      " BROOCH",
      " PENDANT",
    ],
  },
  {
    solutions: [
      {
        category: "UNSPECIFIED QUANTITIES",
        words: ["FEW", " HANDFUL", " SEVERAL", " SOME"],
      },
      {
        category: "NEWSPAPERS",
        words: ["GLOBE", " JOURNAL", " POST", " SUN"],
      },
      {
        category: "CELESTIAL OBJECTS",
        words: ["ASTEROID", " COMET", " MOON", " PLANET"],
      },
      {
        category: "FRUIT HOMOPHONES",
        words: ["LYME", " MELLON", " PAIR", " PLUMB"],
      },
    ],
    allWords: [
      "FEW",
      " HANDFUL",
      " SEVERAL",
      " SOME",
      "GLOBE",
      " JOURNAL",
      " POST",
      " SUN",
      "ASTEROID",
      " COMET",
      " MOON",
      " PLANET",
      "LYME",
      " MELLON",
      " PAIR",
      " PLUMB",
    ],
  },
  {
    solutions: [
      {
        category: "ARACHNIDS",
        words: ["MITE", " SCORPION", " SPIDER", " TICK"],
      },
      {
        category: "FISH",
        words: ["CHAR", " EEL", " PERCH", " SHARK"],
      },
      {
        category: "SUPERHEROES",
        words: ["BLACK WIDOW", " BLADE", " FLASH", " STORM"],
      },
      {
        category: "MTV SHOWS",
        words: ["CATFISH", " CRIBS", " JACKASS", " STATE"],
      },
    ],
    allWords: [
      "MITE",
      " SCORPION",
      " SPIDER",
      " TICK",
      "CHAR",
      " EEL",
      " PERCH",
      " SHARK",
      "BLACK WIDOW",
      " BLADE",
      " FLASH",
      " STORM",
      "CATFISH",
      " CRIBS",
      " JACKASS",
      " STATE",
    ],
  },
  {
    solutions: [
      {
        category: "MOVIE GENRES",
        words: ["HORROR", " MUSICAL", " ROMANCE", " WESTERN"],
      },
      {
        category: "PATTERNS",
        words: ["HOUNDSTOOTH", " PAISLEY", " PLAID", " STRIPES"],
      },
      {
        category: "SYNONYMS FOR FALSEHOOD",
        words: ["FIB", " FICTION", " LIE", " TALE"],
      },
      {
        category: "CANDY PIECES",
        words: ["DOT", " GOOBER", " KISS", " WHOPPER"],
      },
    ],
    allWords: [
      "HORROR",
      " MUSICAL",
      " ROMANCE",
      " WESTERN",
      "HOUNDSTOOTH",
      " PAISLEY",
      " PLAID",
      " STRIPES",
      "FIB",
      " FICTION",
      " LIE",
      " TALE",
      "DOT",
      " GOOBER",
      " KISS",
      " WHOPPER",
    ],
  },
  {
    solutions: [
      {
        category: "CLASSIC ARCADE GAMES",
        words: ["ASTEROIDS", " BREAKOUT", " FROGGER", " PONG"],
      },
      {
        category: "DANCES",
        words: ["HUSTLE", " SALSA", " SWING", " TANGO"],
      },
      {
        category: "TOUCHSCREEN GESTURES",
        words: ["PINCH", " SPREAD", " SWIPE", " TAP"],
      },
      {
        category: "RAPPERS MINUS NUMBERS",
        words: ["CENT", " CHAINZ", " PAC", " SAVAGE"],
      },
    ],
    allWords: [
      "ASTEROIDS",
      " BREAKOUT",
      " FROGGER",
      " PONG",
      "HUSTLE",
      " SALSA",
      " SWING",
      " TANGO",
      "PINCH",
      " SPREAD",
      " SWIPE",
      " TAP",
      "CENT",
      " CHAINZ",
      " PAC",
      " SAVAGE",
    ],
  },
  {
    solutions: [
      {
        category: "CLASSIC TOYS",
        words: ["BLOCKS", " DOLL", " TOP", " YO-YO"],
      },
      {
        category: "WORDS WITH THREE G'S",
        words: ["BAGGAGE", " EGGNOG", " GIGGLE", " LEGGINGS"],
      },
      {
        category: "SHAKESPEARE CHARACTERS",
        words: ["DUNCAN", " JULIET", " PUCK", " VIOLA"],
      },
      {
        category: "___ STICK",
        words: ["FISH", " HOCKEY", " MEMORY", " SELFIE"],
      },
    ],
    allWords: [
      "BLOCKS",
      " DOLL",
      " TOP",
      " YO-YO",
      "BAGGAGE",
      " EGGNOG",
      " GIGGLE",
      " LEGGINGS",
      "DUNCAN",
      " JULIET",
      " PUCK",
      " VIOLA",
      "FISH",
      " HOCKEY",
      " MEMORY",
      " SELFIE",
    ],
  },
  {
    solutions: [
      {
        category: "PLACES FOR WORSHIP",
        words: ["ALTAR", " RELIQUARY", " SHRINE", " TEMPLE"],
      },
      {
        category: "CARTOON CATS",
        words: ["FELIX", " GARFIELD", " SYLVESTER", " TOM"],
      },
      {
        category: "PRESIDENTIAL FIRST NAMES",
        words: ["CALVIN", " CHESTER", " GROVER", " HARRY"],
      },
      {
        category: "___ ROAD",
        words: ["ABBEY", " HIGH", " ROCKY", " SILK"],
      },
    ],
    allWords: [
      "ALTAR",
      " RELIQUARY",
      " SHRINE",
      " TEMPLE",
      "FELIX",
      " GARFIELD",
      " SYLVESTER",
      " TOM",
      "CALVIN",
      " CHESTER",
      " GROVER",
      " HARRY",
      "ABBEY",
      " HIGH",
      " ROCKY",
      " SILK",
    ],
  },
  {
    solutions: [
      {
        category: "ANIMAL GROUP NAMES",
        words: ["COLONY", " HERD", " PRIDE", " SWARM"],
      },
      {
        category: "STONED",
        words: ["BAKED", " BLAZED", " HIGH", " LIT"],
      },
      {
        category: "AP CLASSES",
        words: ["BIO", " CHEM", " GOV", " STATS"],
      },
      {
        category: "TAXONOMY RANKS",
        words: ["CLASS", " DOMAIN", " FAMILY", " ORDER"],
      },
    ],
    allWords: [
      "COLONY",
      " HERD",
      " PRIDE",
      " SWARM",
      "BAKED",
      " BLAZED",
      " HIGH",
      " LIT",
      "BIO",
      " CHEM",
      " GOV",
      " STATS",
      "CLASS",
      " DOMAIN",
      " FAMILY",
      " ORDER",
    ],
  },
  {
    solutions: [
      {
        category: "COMPUTER EQUIPMENT",
        words: ["KEYBOARD", " MONITOR", " MOUSE", " SPEAKER"],
      },
      {
        category: "RODENTS",
        words: ["GERBIL", " HAMSTER", " RAT", " VOLE"],
      },
      {
        category: "MUSICAL INSTRUMENTS",
        words: ["HARP", " HORN", " ORGAN", " TRIANGLE"],
      },
      {
        category: "SYNONYMS FOR COMPLAIN",
        words: ["CARP", " GRIPE", " GROUSE", " MOAN"],
      },
    ],
    allWords: [
      "KEYBOARD",
      " MONITOR",
      " MOUSE",
      " SPEAKER",
      "GERBIL",
      " HAMSTER",
      " RAT",
      " VOLE",
      "HARP",
      " HORN",
      " ORGAN",
      " TRIANGLE",
      "CARP",
      " GRIPE",
      " GROUSE",
      " MOAN",
    ],
  },
  {
    solutions: [
      {
        category: "LONG SANDWICHES",
        words: ["HERO", " HOAGIE", " GRINDER", " SUB"],
      },
      {
        category: "DATING APPS",
        words: ["BUMBLE", " HINGE", " MATCH", " TINDER"],
      },
      {
        category: "VAMPIRE MOVIES",
        words: ["BLADE", " LOST BOYS", " NEAR DARK", " TWILIGHT"],
      },
      {
        category: "ADAMS",
        words: ["ANT", " DRIVER", " SCOTT", " WEST"],
      },
    ],
    allWords: [
      "HERO",
      " HOAGIE",
      " GRINDER",
      " SUB",
      "BUMBLE",
      " HINGE",
      " MATCH",
      " TINDER",
      "BLADE",
      " LOST BOYS",
      " NEAR DARK",
      " TWILIGHT",
      "ANT",
      " DRIVER",
      " SCOTT",
      " WEST",
    ],
  },
  {
    solutions: [
      {
        category: "UNITS OF LENGTH",
        words: ["FOOT", " INCH", " MILE", " YARD"],
      },
      {
        category: "TYPES OF PAINT",
        words: ["ACRYLIC", " OIL", " TEMPERA", " WATERCOLOR"],
      },
      {
        category: "DEEP-FRIED FOOD",
        words: ["FALAFEL", " KATSU", " SAMOSA", " SCHNITZEL"],
      },
      {
        category: "STARTS OF U.S. COINS",
        words: ["DIM", " NICK", " PEN", " QUART"],
      },
    ],
    allWords: [
      "FOOT",
      " INCH",
      " MILE",
      " YARD",
      "ACRYLIC",
      " OIL",
      " TEMPERA",
      " WATERCOLOR",
      "FALAFEL",
      " KATSU",
      " SAMOSA",
      " SCHNITZEL",
      "DIM",
      " NICK",
      " PEN",
      " QUART",
    ],
  },
  {
    solutions: [
      {
        category: "RELATIVES",
        words: ["AUNT", " COUSIN", " MOTHER", " NEPHEW"],
      },
      {
        category: "SYNONYMS FOR OFFBEAT",
        words: ["DAFFY", " KOOKY", " QUIRKY", " WACKY"],
      },
      {
        category: "DISNEY DUCKS",
        words: ["DAISY", " DEWEY", " DONALD", " SCROOGE"],
      },
      {
        category: "___ CLOCK",
        words: ["ALARM", " BIOLOGICAL", " CUCKOO", " GRANDFATHER"],
      },
    ],
    allWords: [
      "AUNT",
      " COUSIN",
      " MOTHER",
      " NEPHEW",
      "DAFFY",
      " KOOKY",
      " QUIRKY",
      " WACKY",
      "DAISY",
      " DEWEY",
      " DONALD",
      " SCROOGE",
      "ALARM",
      " BIOLOGICAL",
      " CUCKOO",
      " GRANDFATHER",
    ],
  },
  {
    solutions: [
      {
        category: "FABRICS",
        words: ["CORDUROY", " DENIM", " LINEN", " TWEED"],
      },
      {
        category: "APPARITIONS",
        words: ["GHOST", " PHANTOM", " SPECTER", " SPIRIT"],
      },
      {
        category: "SYNONYMS FOR BOTHER",
        words: ["NEEDLE", " POKE", " RIB", " TEASE"],
      },
      {
        category: "DISNEY CHARACTERS",
        words: ["BEAST", " GENIE", " SCAR", " STITCH"],
      },
    ],
    allWords: [
      "CORDUROY",
      " DENIM",
      " LINEN",
      " TWEED",
      "GHOST",
      " PHANTOM",
      " SPECTER",
      " SPIRIT",
      "NEEDLE",
      " POKE",
      " RIB",
      " TEASE",
      "BEAST",
      " GENIE",
      " SCAR",
      " STITCH",
    ],
  },
  {
    solutions: [
      {
        category: "BIOMES",
        words: ["DESERT", " FOREST", " GRASSLAND", " TUNDRA"],
      },
      {
        category: "LIZARDS",
        words: ["CHAMELEON", " GECKO", " IGUANA", " MONITOR"],
      },
      {
        category: "YOGA POSES",
        words: ["COBRA", " LOTUS", " TREE", " WARRIOR"],
      },
      {
        category: "DANCES WHEN DOUBLED",
        words: ["CAN", " CHA", " GO", " NAE"],
      },
    ],
    allWords: [
      "DESERT",
      " FOREST",
      " GRASSLAND",
      " TUNDRA",
      "CHAMELEON",
      " GECKO",
      " IGUANA",
      " MONITOR",
      "COBRA",
      " LOTUS",
      " TREE",
      " WARRIOR",
      "CAN",
      " CHA",
      " GO",
      " NAE",
    ],
  },
  {
    solutions: [
      {
        category: "MOVIE TITLE CITIES",
        words: ["CHICAGO", " MUNICH", " PHILADELPHIA", " RIO"],
      },
      {
        category: "FASHION MAGAZINES",
        words: ["ALLURE", " ELLE", " GLAMOUR", " W"],
      },
      {
        category: "STORMS",
        words: ["BLIZZARD", " CYCLONE", " SQUALL", " TORNADO"],
      },
      {
        category: "COCKTAILS",
        words: ["COSMOPOLITAN", " HURRICANE", " MANHATTAN", " SCREWDRIVER"],
      },
    ],
    allWords: [
      "CHICAGO",
      " MUNICH",
      " PHILADELPHIA",
      " RIO",
      "ALLURE",
      " ELLE",
      " GLAMOUR",
      " W",
      "BLIZZARD",
      " CYCLONE",
      " SQUALL",
      " TORNADO",
      "COSMOPOLITAN",
      " HURRICANE",
      " MANHATTAN",
      " SCREWDRIVER",
    ],
  },
  {
    solutions: [
      {
        category: "MODES OF TRANSPORTATION",
        words: ["BOAT", " CAR", " PLANE", " TRAIN"],
      },
      {
        category: "NBA PLAYERS",
        words: ["KING", " MAGIC", " SUN", " THUNDER"],
      },
      {
        category: "FAST FOOD CHAINS",
        words: ["CHECKERS", " OUTBACK", " SONIC", " SUBWAY"],
      },
      {
        category: "BAND NAMES MINUS COLORS",
        words: ["DAY", " FLOYD", " SABBATH", " STRIPES"],
      },
    ],
    allWords: [
      "BOAT",
      " CAR",
      " PLANE",
      " TRAIN",
      "KING",
      " MAGIC",
      " SUN",
      " THUNDER",
      "CHECKERS",
      " OUTBACK",
      " SONIC",
      " SUBWAY",
      "DAY",
      " FLOYD",
      " SABBATH",
      " STRIPES",
    ],
  },
  {
    solutions: [
      {
        category: "STATES OF MATTER",
        words: ["GAS", " LIQUID", " PLASMA", " SOLID"],
      },
      {
        category: "EDIT MENU COMMANDS",
        words: ["COPY", " CUT", " PASTE", " UNDO"],
      },
      {
        category: "DEFEAT BADLY",
        words: ["CRUSH", " ROUT", " SHELLAC", " TRASH"],
      },
      {
        category: "ANAGRAMS",
        words: ["LEAST", " SLATE", " STALE", " TESLA"],
      },
    ],
    allWords: [
      "GAS",
      " LIQUID",
      " PLASMA",
      " SOLID",
      "COPY",
      " CUT",
      " PASTE",
      " UNDO",
      "CRUSH",
      " ROUT",
      " SHELLAC",
      " TRASH",
      "LEAST",
      " SLATE",
      " STALE",
      " TESLA",
    ],
  },
  {
    solutions: [
      {
        category: "SYNONYMS FOR ANGRY",
        words: ["FURIOUS", " INCENSED", " IRATE", " LIVID"],
      },
      {
        category: "THINGS THAT ARE YELLOW",
        words: ["BANANA", " CANARY", " SCHOOL BUS", " SUNFLOWER"],
      },
      {
        category: "MARINE BIRDS",
        words: ["BOOBY", " GULL", " PELICAN", " PUFFIN"],
      },
      {
        category: "___ BOYS",
        words: ["BEACH", " BEASTIE", " HARDY", " LOST"],
      },
    ],
    allWords: [
      "FURIOUS",
      " INCENSED",
      " IRATE",
      " LIVID",
      "BANANA",
      " CANARY",
      " SCHOOL BUS",
      " SUNFLOWER",
      "BOOBY",
      " GULL",
      " PELICAN",
      " PUFFIN",
      "BEACH",
      " BEASTIE",
      " HARDY",
      " LOST",
    ],
  },
  {
    solutions: [
      {
        category: "SCUBA GEAR",
        words: ["FINS", " MASK", " SNORKEL", " TANK"],
      },
      {
        category: "PUNCTUATION MARKS",
        words: ["COLON", " COMMA", " HYPHEN", " PERIOD"],
      },
      {
        category: "RUN QUICKLY",
        words: ["BOLT", " DASH", " RACE", " SPRINT"],
      },
      {
        category: "___ CAT",
        words: ["DOJA", " FAT", " HOUSE", " JUNGLE"],
      },
    ],
    allWords: [
      "FINS",
      " MASK",
      " SNORKEL",
      " TANK",
      "COLON",
      " COMMA",
      " HYPHEN",
      " PERIOD",
      "BOLT",
      " DASH",
      " RACE",
      " SPRINT",
      "DOJA",
      " FAT",
      " HOUSE",
      " JUNGLE",
    ],
  },
  {
    solutions: [
      {
        category: "BOTTLED WATER BRANDS",
        words: ["DASANI", " EVIAN", " FIJI", " VOSS"],
      },
      {
        category: "SLANG FOR COFFEE",
        words: ["BREW", " JAVA", " JOE", " MUD"],
      },
      {
        category: "ISLAND COUNTRIES",
        words: ["CUBA", " JAPAN", " MALTA", " PALAU"],
      },
      {
        category: "CEREAL MASCOTS",
        words: ["LUCKY", " POP", " SAM", " TONY"],
      },
    ],
    allWords: [
      "DASANI",
      " EVIAN",
      " FIJI",
      " VOSS",
      "BREW",
      " JAVA",
      " JOE",
      " MUD",
      "CUBA",
      " JAPAN",
      " MALTA",
      " PALAU",
      "LUCKY",
      " POP",
      " SAM",
      " TONY",
    ],
  },
  {
    solutions: [
      {
        category: "WOODWINDS",
        words: ["BASSOON", " CLARINET", " FLUTE", " OBOE"],
      },
      {
        category: "COVERINGS",
        words: ["CAP", " COVER", " LID", " TOP"],
      },
      {
        category: "SUNGLASSES",
        words: ["AVIATOR", " CAT EYE", " WAYFARER", " WRAPAROUND"],
      },
      {
        category: "SEALS",
        words: ["HARBOR", " HARP", " HOODED", " MONK"],
      },
    ],
    allWords: [
      "BASSOON",
      " CLARINET",
      " FLUTE",
      " OBOE",
      "CAP",
      " COVER",
      " LID",
      " TOP",
      "AVIATOR",
      " CAT EYE",
      " WAYFARER",
      " WRAPAROUND",
      "HARBOR",
      " HARP",
      " HOODED",
      " MONK",
    ],
  },
  {
    solutions: [
      {
        category: "TIMEKEEPING DEVICES",
        words: ["CLOCK", " HOURGLASS", " SUNDIAL", " WATCH"],
      },
      {
        category: "HAIRSTYLES",
        words: ["BOB", " CROP", " PIXIE", " SHAG"],
      },
      {
        category: "UNITS OF MEASURE",
        words: ["HERTZ", " MOLE", " NEWTON", " SECOND"],
      },
      {
        category: "DR. ___",
        words: ["EVIL", " J", " NO", " PEPPER"],
      },
    ],
    allWords: [
      "CLOCK",
      " HOURGLASS",
      " SUNDIAL",
      " WATCH",
      "BOB",
      " CROP",
      " PIXIE",
      " SHAG",
      "HERTZ",
      " MOLE",
      " NEWTON",
      " SECOND",
      "EVIL",
      " J",
      " NO",
      " PEPPER",
    ],
  },
  {
    solutions: [
      {
        category: "TREES",
        words: ["ASH", " CEDAR", " MAPLE", " PINE"],
      },
      {
        category: "LAND FORMATIONS",
        words: ["HILL", " MOUNTAIN", " PLATEAU", " VALLEY"],
      },
      {
        category: "BAGEL FLAVORS",
        words: ["EVERYTHING", " ONION", " PLAIN", " POPPY"],
      },
      {
        category: "STREETS ON SCREEN",
        words: ["ELM", " FEAR", " JUMP", " SESAME"],
      },
    ],
    allWords: [
      "ASH",
      " CEDAR",
      " MAPLE",
      " PINE",
      "HILL",
      " MOUNTAIN",
      " PLATEAU",
      " VALLEY",
      "EVERYTHING",
      " ONION",
      " PLAIN",
      " POPPY",
      "ELM",
      " FEAR",
      " JUMP",
      " SESAME",
    ],
  },
  {
    solutions: [
      {
        category: "MARINE MAMMALS",
        words: ["DOLPHIN", " MANATEE", " OTTER", " SEAL"],
      },
      {
        category: "BIKE PARTS",
        words: ["BRAKE", " CHAIN", " SADDLE", " SPOKE"],
      },
      {
        category: "SYNONYMS FOR SELL",
        words: ["HAWK", " MOVE", " PEDDLE", " VEND"],
      },
      {
        category: 'COUNTRIES WHEN "A" IS ADDED',
        words: ["CHIN", " CUB", " MALT", " TONG"],
      },
    ],
    allWords: [
      "DOLPHIN",
      " MANATEE",
      " OTTER",
      " SEAL",
      "BRAKE",
      " CHAIN",
      " SADDLE",
      " SPOKE",
      "HAWK",
      " MOVE",
      " PEDDLE",
      " VEND",
      "CHIN",
      " CUB",
      " MALT",
      " TONG",
    ],
  },
  {
    solutions: [
      {
        category: "MARSUPIALS",
        words: ["KANGAROO", " KOALA", " WALLABY", " WOMBAT"],
      },
      {
        category: "CHOCOLATE BARS",
        words: ["CHUNKY", " CRUNCH", " MARS", " MOUNDS"],
      },
      {
        category: "SLANG FOR MONEY",
        words: ["CHEDDAR", " DOUGH", " PAPER", " STACKS"],
      },
      {
        category: "NAKED ___",
        words: ["EYE", " GUN", " MOLE RAT", " TRUTH"],
      },
    ],
    allWords: [
      "KANGAROO",
      " KOALA",
      " WALLABY",
      " WOMBAT",
      "CHUNKY",
      " CRUNCH",
      " MARS",
      " MOUNDS",
      "CHEDDAR",
      " DOUGH",
      " PAPER",
      " STACKS",
      "EYE",
      " GUN",
      " MOLE RAT",
      " TRUTH",
    ],
  },
  {
    solutions: [
      {
        category: "U.S. COINS",
        words: ["DIME", " NICKEL", " PENNY", " QUARTER"],
      },
      {
        category: "METAL ELEMENTS",
        words: ["IRON", " LEAD", " TIN", " ZINC"],
      },
      {
        category: "LUCKY CHARMS MARSHMALLOWS",
        words: ["CLOVER", " HORSESHOE", " MOON", " RAINBOW"],
      },
      {
        category: "___ AND ___",
        words: ["AGAIN", " HALF", " NECK", " SO"],
      },
    ],
    allWords: [
      "DIME",
      " NICKEL",
      " PENNY",
      " QUARTER",
      "IRON",
      " LEAD",
      " TIN",
      " ZINC",
      "CLOVER",
      " HORSESHOE",
      " MOON",
      " RAINBOW",
      "AGAIN",
      " HALF",
      " NECK",
      " SO",
    ],
  },
  {
    solutions: [
      {
        category: "PLEASANT SMELLS",
        words: ["AROMA", " BOUQUET", " FRAGRANCE", " SCENT"],
      },
      {
        category: "MUSIC GENRES",
        words: ["BLUES", " COUNTRY", " FUNK", " SOUL"],
      },
      {
        category: "ROCK PAPER SCISSORS",
        words: ["PAPER", " ROCK", " SCISSORS", " SHOOT"],
      },
      {
        category: "MALE ANIMALS",
        words: ["BOAR", " BUCK", " BULL", " JACK"],
      },
    ],
    allWords: [
      "AROMA",
      " BOUQUET",
      " FRAGRANCE",
      " SCENT",
      "BLUES",
      " COUNTRY",
      " FUNK",
      " SOUL",
      "PAPER",
      " ROCK",
      " SCISSORS",
      " SHOOT",
      "BOAR",
      " BUCK",
      " BULL",
      " JACK",
    ],
  },
  {
    solutions: [
      {
        category: "BOATS",
        words: ["FERRY", " JUNK", " TUG", " YACHT"],
      },
      {
        category: "SANDWICHES",
        words: ["CLUB", " CUBAN", " MELT", " SUB"],
      },
      {
        category: "CUTS OF BEEF",
        words: ["FLANK", " LOIN", " ROUND", " SHANK"],
      },
      {
        category: "NICKNAMES THAT ARE VERBS",
        words: ["CHUCK", " JOSH", " ROB", " SUE"],
      },
    ],
    allWords: [
      "FERRY",
      " JUNK",
      " TUG",
      " YACHT",
      "CLUB",
      " CUBAN",
      " MELT",
      " SUB",
      "FLANK",
      " LOIN",
      " ROUND",
      " SHANK",
      "CHUCK",
      " JOSH",
      " ROB",
      " SUE",
    ],
  },
  {
    solutions: [
      {
        category: "SHOE PARTS",
        words: ["HEEL", " LACE", " SOLE", " TONGUE"],
      },
      {
        category: "BOARD GAMES",
        words: ["CLUE", " RISK", " SORRY", " TROUBLE"],
      },
      {
        category: "FICTIONAL SPIES",
        words: ["BOND", " HUNT", " RYAN", " SMART"],
      },
      {
        category: "RUBBER ___",
        words: ["BAND", " CEMENT", " DUCKIE", " SOUL"],
      },
    ],
    allWords: [
      "HEEL",
      " LACE",
      " SOLE",
      " TONGUE",
      "CLUE",
      " RISK",
      " SORRY",
      " TROUBLE",
      "BOND",
      " HUNT",
      " RYAN",
      " SMART",
      "BAND",
      " CEMENT",
      " DUCKIE",
      " SOUL",
    ],
  },
  {
    solutions: [
      {
        category: "VEGETABLES THAT ARE ALSO FRUITS",
        words: ["CUCUMBER", " EGGPLANT", " PEPPER", " TOMATO"],
      },
      {
        category: "3-D SHAPES",
        words: ["CONE", " CUBE", " PYRAMID", " SPHERE"],
      },
      {
        category: 'WORDS WITH "i"',
        words: ["MAC", " PAD", " PHONE", " POD"],
      },
      {
        category: "WORDS WITH TWO PRONUNCIATIONS",
        words: ["JOB", " LIMA", " MOBILE", " POLISH"],
      },
    ],
    allWords: [
      "CUCUMBER",
      " EGGPLANT",
      " PEPPER",
      " TOMATO",
      "CONE",
      " CUBE",
      " PYRAMID",
      " SPHERE",
      "MAC",
      " PAD",
      " PHONE",
      " POD",
      "JOB",
      " LIMA",
      " MOBILE",
      " POLISH",
    ],
  },
  {
    solutions: [
      {
        category: "NFL PLAYERS",
        words: ["BRONCO", " COWBOY", " PACKER", " RAVEN"],
      },
      {
        category: "PASTA SHAPES",
        words: ["BOWTIE", " ELBOW", " SHELL", " SPIRAL"],
      },
      {
        category: "JOINTS",
        words: ["HIP", " KNEE", " SHOULDER", " WRIST"],
      },
      {
        category: 'MOVIES WITH "!"',
        words: ["AIRPLANE", " MOTHER", " OKLAHOMA", " THEM"],
      },
    ],
    allWords: [
      "BRONCO",
      " COWBOY",
      " PACKER",
      " RAVEN",
      "BOWTIE",
      " ELBOW",
      " SHELL",
      " SPIRAL",
      "HIP",
      " KNEE",
      " SHOULDER",
      " WRIST",
      "AIRPLANE",
      " MOTHER",
      " OKLAHOMA",
      " THEM",
    ],
  },
  {
    solutions: [
      {
        category: "WINGED INSECTS",
        words: ["FLY", " GNAT", " MOTH", " WASP"],
      },
      {
        category: "ARITHMETIC OPERATIONS",
        words: ["ADD", " DIVIDE", " MULTIPLY", " SUBTRACT"],
      },
      {
        category: "FISH",
        words: ["TANG", " TETRA", " SKATE", " SOLE"],
      },
      {
        category: "___ CAT",
        words: ["ALLEY", " COOL", " COPY", " LAP"],
      },
    ],
    allWords: [
      "FLY",
      " GNAT",
      " MOTH",
      " WASP",
      "ADD",
      " DIVIDE",
      " MULTIPLY",
      " SUBTRACT",
      "TANG",
      " TETRA",
      " SKATE",
      " SOLE",
      "ALLEY",
      " COOL",
      " COPY",
      " LAP",
    ],
  },
  {
    solutions: [
      {
        category: "SEVEN DWARFS",
        words: ["BASHFUL", " DOC", " GRUMPY", " HAPPY"],
      },
      {
        category: "FILE EXTENSIONS",
        words: ["GIF", " PDF", " TIFF", " ZIP"],
      },
      {
        category: "FLIGHTLESS BIRDS",
        words: ["EMU", " KIWI", " OSTRICH", " PENGUIN"],
      },
      {
        category: "TROPICAL FRUITS",
        words: ["BANANA", " COCONUT", " MANGO", " PINEAPPLE"],
      },
    ],
    allWords: [
      "BASHFUL",
      " DOC",
      " GRUMPY",
      " HAPPY",
      "GIF",
      " PDF",
      " TIFF",
      " ZIP",
      "EMU",
      " KIWI",
      " OSTRICH",
      " PENGUIN",
      "BANANA",
      " COCONUT",
      " MANGO",
      " PINEAPPLE",
    ],
  },
  {
    solutions: [
      {
        category: "HATS",
        words: ["BERET", " BOWLER", " FEDORA", " FEZ"],
      },
      {
        category: "ORGANS",
        words: ["HEART", " KIDNEY", " LIVER", " LUNG"],
      },
      {
        category: "PARTS OF A BOOK",
        words: ["COVER", " JACKET", " PAGE", " SPINE"],
      },
      {
        category: "JACK ___",
        words: ["ASS", " KNIFE", " POT", " RABBIT"],
      },
    ],
    allWords: [
      "BERET",
      " BOWLER",
      " FEDORA",
      " FEZ",
      "HEART",
      " KIDNEY",
      " LIVER",
      " LUNG",
      "COVER",
      " JACKET",
      " PAGE",
      " SPINE",
      "ASS",
      " KNIFE",
      " POT",
      " RABBIT",
    ],
  },
  {
    solutions: [
      {
        category: "EUROPEAN COUNTRIES",
        words: ["DENMARK", " GREECE", " POLAND", " PORTUGAL"],
      },
      {
        category: "SYNONYMS FOR IMITATE",
        words: ["COPY", " ECHO", " MIMIC", " PARROT"],
      },
      {
        category: "TOMS",
        words: ["CRUISE", " HOLLAND", " PETTY", " WAITS"],
      },
      {
        category: "WORDS SPELLED WITH ROMAN NUMERALS",
        words: ["DILL", " LIVID", " MILD", " MIX"],
      },
    ],
    allWords: [
      "DENMARK",
      " GREECE",
      " POLAND",
      " PORTUGAL",
      "COPY",
      " ECHO",
      " MIMIC",
      " PARROT",
      "CRUISE",
      " HOLLAND",
      " PETTY",
      " WAITS",
      "DILL",
      " LIVID",
      " MILD",
      " MIX",
    ],
  },
  {
    solutions: [
      {
        category: "DESSERTS",
        words: ["CHEESECAKE", " FLAN", " MOUSSE", " TIRAMISU"],
      },
      {
        category: "MILD OATHS",
        words: ["DARN", " FUDGE", " HECK", " SHOOT"],
      },
      {
        category: "ANIMALS WITH TUSKS",
        words: ["ELEPHANT", " HIPPO", " NARWHAL", " WARTHOG"],
      },
      {
        category: "MUSTACHES",
        words: ["HANDLEBAR", " HORSESHOE", " PENCIL", " WALRUS"],
      },
    ],
    allWords: [
      "CHEESECAKE",
      " FLAN",
      " MOUSSE",
      " TIRAMISU",
      "DARN",
      " FUDGE",
      " HECK",
      " SHOOT",
      "ELEPHANT",
      " HIPPO",
      " NARWHAL",
      " WARTHOG",
      "HANDLEBAR",
      " HORSESHOE",
      " PENCIL",
      " WALRUS",
    ],
  },
  {
    solutions: [
      {
        category: "CANDY BARS",
        words: ["BOUNTY", " CRUNCH", " HEATH", " MILKY WAY"],
      },
      {
        category: "VIDEO GAME CONSOLES",
        words: ["DREAMCAST", " GENESIS", " SWITCH", " WII"],
      },
      {
        category: "EAR PARTS",
        words: ["ANVIL", " COCHLEA", " HAMMER", " STIRRUP"],
      },
      {
        category: "BAND NAMES MINUS NUMBERS",
        words: ["BLINK", " MAROON", " SUM", " U"],
      },
    ],
    allWords: [
      "BOUNTY",
      " CRUNCH",
      " HEATH",
      " MILKY WAY",
      "DREAMCAST",
      " GENESIS",
      " SWITCH",
      " WII",
      "ANVIL",
      " COCHLEA",
      " HAMMER",
      " STIRRUP",
      "BLINK",
      " MAROON",
      " SUM",
      " U",
    ],
  },
  {
    solutions: [
      {
        category: "60's BAND MEMBERS",
        words: ["BEACH BOY", " BEATLE", " BYRD", " MONKEE"],
      },
      {
        category: "DANCE FADS",
        words: ["DOUGIE", " MACARENA", " MASHED POTATO", " TWIST"],
      },
      {
        category: "MAGAZINES",
        words: ["FORTUNE", " ROLLING STONE", " VOGUE", " WIRED"],
      },
      {
        category: "THINGS WITH LINKS",
        words: ["CHAIN", " GOLF COURSE", " SAUSAGE", " WEBSITE"],
      },
    ],
    allWords: [
      "BEACH BOY",
      " BEATLE",
      " BYRD",
      " MONKEE",
      "DOUGIE",
      " MACARENA",
      " MASHED POTATO",
      " TWIST",
      "FORTUNE",
      " ROLLING STONE",
      " VOGUE",
      " WIRED",
      "CHAIN",
      " GOLF COURSE",
      " SAUSAGE",
      " WEBSITE",
    ],
  },
  {
    solutions: [
      {
        category: "DOG BREEDS",
        words: ["BOXER", " DALMATIAN", " HUSKY", " POODLE"],
      },
      {
        category: "ANIMAL NOSES",
        words: ["BEAK", " MUZZLE", " SNOUT", " TRUNK"],
      },
      {
        category: "TRAFFIC SIGNS",
        words: ["DETOUR", " SLOW", " STOP", " YIELD"],
      },
      {
        category: "SOUND ___",
        words: ["ASLEEP", " BARRIER", " BITE", " WAVE"],
      },
    ],
    allWords: [
      "BOXER",
      " DALMATIAN",
      " HUSKY",
      " POODLE",
      "BEAK",
      " MUZZLE",
      " SNOUT",
      " TRUNK",
      "DETOUR",
      " SLOW",
      " STOP",
      " YIELD",
      "ASLEEP",
      " BARRIER",
      " BITE",
      " WAVE",
    ],
  },
  {
    solutions: [
      {
        category: "MUSIC GENRES",
        words: ["JAZZ", " POP", " PUNK", " RAP"],
      },
      {
        category: "WEB BROWSERS",
        words: ["CHROME", " EDGE", " OPERA", " SAFARI"],
      },
      {
        category: '"LITTLE WOMEN" SISTERS',
        words: ["AMY", " BETH", " JO", " MEG"],
      },
      {
        category: "LIL ___ RAPPERS",
        words: ["BABY", " JON", " KIM", " WAYNE"],
      },
    ],
    allWords: [
      "JAZZ",
      " POP",
      " PUNK",
      " RAP",
      "CHROME",
      " EDGE",
      " OPERA",
      " SAFARI",
      "AMY",
      " BETH",
      " JO",
      " MEG",
      "BABY",
      " JON",
      " KIM",
      " WAYNE",
    ],
  },
  {
    solutions: [
      {
        category: "GRAINS",
        words: ["BARLEY", " OAT", " RYE", " SPELT"],
      },
      {
        category: "ROYAL TITLES",
        words: ["BARON", " EARL", " KING", " PRINCE"],
      },
      {
        category: "UNIVERSITIES",
        words: ["BROWN", " DUKE", " HOWARD", " RICE"],
      },
      {
        category: "BEST DIRECTOR OSCAR WINNERS",
        words: ["BONG", " FORD", " LEE", " STONE"],
      },
    ],
    allWords: [
      "BARLEY",
      " OAT",
      " RYE",
      " SPELT",
      "BARON",
      " EARL",
      " KING",
      " PRINCE",
      "BROWN",
      " DUKE",
      " HOWARD",
      " RICE",
      "BONG",
      " FORD",
      " LEE",
      " STONE",
    ],
  },
  {
    solutions: [
      {
        category: "OFF-WHITE SHADES",
        words: ["CREAM", " EGGSHELL", " IVORY", " VANILLA"],
      },
      {
        category: "ANTI-VAMPIRE",
        words: ["CRUCIFIX", " GARLIC", " MIRROR", " STAKE"],
      },
      {
        category: "KINDS OF MEAT",
        words: ["BEEF", " PORK", " POULTRY", " VENISON"],
      },
      {
        category: "SYNONYMS FOR ARGUMENT",
        words: ["ROW", " QUARREL", " SPAT", " TIFF"],
      },
    ],
    allWords: [
      "CREAM",
      " EGGSHELL",
      " IVORY",
      " VANILLA",
      "CRUCIFIX",
      " GARLIC",
      " MIRROR",
      " STAKE",
      "BEEF",
      " PORK",
      " POULTRY",
      " VENISON",
      "ROW",
      " QUARREL",
      " SPAT",
      " TIFF",
    ],
  },
  {
    solutions: [
      {
        category: "MUSCLES, INFORMALLY",
        words: ["LAT", " PEC", " QUAD", " TRI"],
      },
      {
        category: "AWARDS",
        words: ["CUP", " MEDAL", " RIBBON", " TROPHY"],
      },
      {
        category: "TITLE TV DOCTORS",
        words: ["GREY", " HOUSE", " HOWSER", " QUINN"],
      },
      {
        category: "NFL PLAYERS",
        words: ["BEAR", " BILL", " BROWN", " COMMANDER"],
      },
    ],
    allWords: [
      "LAT",
      " PEC",
      " QUAD",
      " TRI",
      "CUP",
      " MEDAL",
      " RIBBON",
      " TROPHY",
      "GREY",
      " HOUSE",
      " HOWSER",
      " QUINN",
      "BEAR",
      " BILL",
      " BROWN",
      " COMMANDER",
    ],
  },
  {
    solutions: [
      {
        category: "NECKWEAR",
        words: ["ASCOT", " BOLO", " SCARF", " TIE"],
      },
      {
        category: "SHIP DIRECTIONS",
        words: ["BOW", " PORT", " STARBOARD", " STERN"],
      },
      {
        category: "DETERGENTS",
        words: ["ALL", " ERA", " GAIN", " TIDE"],
      },
      {
        category: "___ TRIANGLE",
        words: ["ACUTE", " BERMUDA", " LOVE", " RIGHT"],
      },
    ],
    allWords: [
      "ASCOT",
      " BOLO",
      " SCARF",
      " TIE",
      "BOW",
      " PORT",
      " STARBOARD",
      " STERN",
      "ALL",
      " ERA",
      " GAIN",
      " TIDE",
      "ACUTE",
      " BERMUDA",
      " LOVE",
      " RIGHT",
    ],
  },
  {
    solutions: [
      {
        category: "COFFEE DRINKS",
        words: ["AMERICANO", " CAPPUCCINO", " ESPRESSO", " LATTE"],
      },
      {
        category: "TREE NUTS",
        words: ["ALMOND", " CASHEW", " PECAN", " WALNUT"],
      },
      {
        category: "SHADES OF GREEN",
        words: ["EMERALD", " FOREST", " KELLY", " OLIVE"],
      },
      {
        category: "MR. ___",
        words: ["BEAN", " CLEAN", " FOX", " PEANUT"],
      },
    ],
    allWords: [
      "AMERICANO",
      " CAPPUCCINO",
      " ESPRESSO",
      " LATTE",
      "ALMOND",
      " CASHEW",
      " PECAN",
      " WALNUT",
      "EMERALD",
      " FOREST",
      " KELLY",
      " OLIVE",
      "BEAN",
      " CLEAN",
      " FOX",
      " PEANUT",
    ],
  },
  {
    solutions: [
      {
        category: "BIRD SOUNDS",
        words: ["CAW", " CHIRP", " CLUCK", " TWEET"],
      },
      {
        category: "COLORS",
        words: ["BROWN", " PINK", " TURQUOISE", " VIOLET"],
      },
      {
        category: "FISHING GEAR",
        words: ["LURE", " REEL", " ROD", " TACKLE"],
      },
      {
        category: "FICTIONAL PIRATES",
        words: ["HOOK", " JONES", " SILVER", " SPARROW"],
      },
    ],
    allWords: [
      "CAW",
      " CHIRP",
      " CLUCK",
      " TWEET",
      "BROWN",
      " PINK",
      " TURQUOISE",
      " VIOLET",
      "LURE",
      " REEL",
      " ROD",
      " TACKLE",
      "HOOK",
      " JONES",
      " SILVER",
      " SPARROW",
    ],
  },
  {
    solutions: [
      {
        category: "BEDS",
        words: ["BUNK", " CANOPY", " MURPHY", " TRUNDLE"],
      },
      {
        category: "FAMOUS BROTHERS",
        words: ["JONAS", " MARX", " WARNER", " WRIGHT"],
      },
      {
        category: "HONDAS",
        words: ["ACCORD", " CIVIC", " PASSPORT", " PILOT"],
      },
      {
        category: "VIDEO GAME CHARACTERS",
        words: ["CRASH", " LINK", " MARIO", " SONIC"],
      },
    ],
    allWords: [
      "BUNK",
      " CANOPY",
      " MURPHY",
      " TRUNDLE",
      "JONAS",
      " MARX",
      " WARNER",
      " WRIGHT",
      "ACCORD",
      " CIVIC",
      " PASSPORT",
      " PILOT",
      "CRASH",
      " LINK",
      " MARIO",
      " SONIC",
    ],
  },
  {
    solutions: [
      {
        category: "AIRLINES",
        words: ["FRONTIER", " SPIRIT", " UNITED", " VIRGIN"],
      },
      {
        category: "GREEK LETTERS",
        words: ["BETA", " CHI", " DELTA", " IOTA"],
      },
      {
        category: 'SILENT "G"',
        words: ["GNAT", " GNAW", " GNOCCHI", " GNOME"],
      },
      {
        category: "HOMOPHONES",
        words: ["GNU", " KNEW", " NEW", " NU"],
      },
    ],
    allWords: [
      "FRONTIER",
      " SPIRIT",
      " UNITED",
      " VIRGIN",
      "BETA",
      " CHI",
      " DELTA",
      " IOTA",
      "GNAT",
      " GNAW",
      " GNOCCHI",
      " GNOME",
      "GNU",
      " KNEW",
      " NEW",
      " NU",
    ],
  },
  {
    solutions: [
      {
        category: "ANIMAL GROUP NAMES",
        words: ["FLOCK", " PACK", " POD", " SCHOOL"],
      },
      {
        category: "DEADLY SINS",
        words: ["ENVY", " GREED", " LUST", " PRIDE"],
      },
      {
        category: "SLOW ANIMALS",
        words: ["LORIS", " SLOTH", " SNAIL", " TORTOISE"],
      },
      {
        category: "TRIG FUNCTIONS",
        words: ["COT", " SEC", " SIN", " TAN"],
      },
    ],
    allWords: [
      "FLOCK",
      " PACK",
      " POD",
      " SCHOOL",
      "ENVY",
      " GREED",
      " LUST",
      " PRIDE",
      "LORIS",
      " SLOTH",
      " SNAIL",
      " TORTOISE",
      "COT",
      " SEC",
      " SIN",
      " TAN",
    ],
  },
  {
    solutions: [
      {
        category: 'SPICES BEGINNING WITH "C"',
        words: ["CARDAMOM", " CLOVE", " CORIANDER", " CUMIN"],
      },
      {
        category: "TERMS OF ENDEARMENT",
        words: ["BOO", " HONEY", " SUGAR", " SWEETIE"],
      },
      {
        category: "THINGS WITH WINGS",
        words: ["AIRPLANE", " ANGEL", " BIRD", " PEGASUS"],
      },
      {
        category: "SPICE GIRLS",
        words: ["BABY", " GINGER", " POSH", " SCARY"],
      },
    ],
    allWords: [
      "CARDAMOM",
      " CLOVE",
      " CORIANDER",
      " CUMIN",
      "BOO",
      " HONEY",
      " SUGAR",
      " SWEETIE",
      "AIRPLANE",
      " ANGEL",
      " BIRD",
      " PEGASUS",
      "BABY",
      " GINGER",
      " POSH",
      " SCARY",
    ],
  },
  {
    solutions: [
      {
        category: "FRUIT",
        words: ["DATE", " KIWI", " LEMON", " ORANGE"],
      },
      {
        category: "COUNTRIES",
        words: ["CHAD", " GEORGIA", " JORDAN", " TOGO"],
      },
      {
        category: "BIRDS",
        words: ["CRANE", " JAY", " SWALLOW", " TURKEY"],
      },
      {
        category: "ZODIAC SYMBOLS",
        words: ["FISH", " GOAT", " SCALES", " TWINS"],
      },
    ],
    allWords: [
      "DATE",
      " KIWI",
      " LEMON",
      " ORANGE",
      "CHAD",
      " GEORGIA",
      " JORDAN",
      " TOGO",
      "CRANE",
      " JAY",
      " SWALLOW",
      " TURKEY",
      "FISH",
      " GOAT",
      " SCALES",
      " TWINS",
    ],
  },
  {
    solutions: [
      {
        category: "SPORTS",
        words: ["CRICKET", " FENCING", " POLO", " SQUASH"],
      },
      {
        category: "TOPS",
        words: ["CAMI", " HALTER", " TANK", " TEE"],
      },
      {
        category: "VEGETABLES",
        words: ["BEET", " CARROT", " CORN", " ONION"],
      },
      {
        category: "INSECTS",
        words: ["ANT", " BEETLE", " MANTIS", " TERMITE"],
      },
    ],
    allWords: [
      "CRICKET",
      " FENCING",
      " POLO",
      " SQUASH",
      "CAMI",
      " HALTER",
      " TANK",
      " TEE",
      "BEET",
      " CARROT",
      " CORN",
      " ONION",
      "ANT",
      " BEETLE",
      " MANTIS",
      " TERMITE",
    ],
  },
  {
    solutions: [
      {
        category: "BOARD GAMES",
        words: ["BACKGAMMON", " CHECKERS", " CHESS", " GO"],
      },
      {
        category: "MATTRESS SIZES",
        words: ["FULL", " KING", " QUEEN", " TWIN"],
      },
      {
        category: "THINGS THAT ARE RED",
        words: ["CHERRY", " FIRE TRUCK", " RUBY", " STOP SIGN"],
      },
      {
        category: "THINGS WITH KEYS",
        words: ["CRYPTOGRAPHY", " FLORIDA", " LOCKSMITH", " PIANO"],
      },
    ],
    allWords: [
      "BACKGAMMON",
      " CHECKERS",
      " CHESS",
      " GO",
      "FULL",
      " KING",
      " QUEEN",
      " TWIN",
      "CHERRY",
      " FIRE TRUCK",
      " RUBY",
      " STOP SIGN",
      "CRYPTOGRAPHY",
      " FLORIDA",
      " LOCKSMITH",
      " PIANO",
    ],
  },
  {
    solutions: [
      {
        category: "LEG PARTS",
        words: ["ANKLE", " KNEE", " SHIN", " THIGH"],
      },
      {
        category: "BABY ANIMALS",
        words: ["CALF", " CUB", " JOEY", " KID"],
      },
      {
        category: "SLANG FOR TOILET",
        words: ["CAN", " HEAD", " JOHN", " THRONE"],
      },
      {
        category: "___ FISH THAT AREN'T FISH",
        words: ["CRAY", " JELLY", " SILVER", " STAR"],
      },
    ],
    allWords: [
      "ANKLE",
      " KNEE",
      " SHIN",
      " THIGH",
      "CALF",
      " CUB",
      " JOEY",
      " KID",
      "CAN",
      " HEAD",
      " JOHN",
      " THRONE",
      "CRAY",
      " JELLY",
      " SILVER",
      " STAR",
    ],
  },
  {
    solutions: [
      {
        category: "MONOPOLY SQUARES",
        words: ["BOARDWALK", " CHANCE", " GO", " JAIL"],
      },
      {
        category: "SHADES OF BLUE",
        words: ["BABY", " MIDNIGHT", " POWDER", " ROYAL"],
      },
      {
        category: "RAPPERS",
        words: ["COMMON", " FUTURE", " ICE CUBE", " Q-TIP"],
      },
      {
        category: "MEMBERS OF A SEPTET",
        words: ["SEA", " SIN", " SISTER", " WONDER"],
      },
    ],
    allWords: [
      "BOARDWALK",
      " CHANCE",
      " GO",
      " JAIL",
      "BABY",
      " MIDNIGHT",
      " POWDER",
      " ROYAL",
      "COMMON",
      " FUTURE",
      " ICE CUBE",
      " Q-TIP",
      "SEA",
      " SIN",
      " SISTER",
      " WONDER",
    ],
  },
  {
    solutions: [
      {
        category: "STREAMING SERVICES",
        words: ["HULU", " NETFLIX", " PEACOCK", " PRIME"],
      },
      {
        category: "CONDIMENTS",
        words: ["KETCHUP", " MAYO", " RELISH", " TARTAR"],
      },
      {
        category: "SYNONYMS FOR SAD",
        words: ["BLUE", " DOWN", " GLUM", " LOW"],
      },
      {
        category: "CLUE CHARACTERS",
        words: ["GREEN", " MUSTARD", " PLUM", " SCARLET"],
      },
    ],
    allWords: [
      "HULU",
      " NETFLIX",
      " PEACOCK",
      " PRIME",
      "KETCHUP",
      " MAYO",
      " RELISH",
      " TARTAR",
      "BLUE",
      " DOWN",
      " GLUM",
      " LOW",
      "GREEN",
      " MUSTARD",
      " PLUM",
      " SCARLET",
    ],
  },
  {
    solutions: [
      {
        category: "SNEAKER BRANDS",
        words: ["ADIDAS", " NIKE", " PUMA", " REEBOK"],
      },
      {
        category: 'MUSICALS BEGINNING WITH "C"',
        words: ["CABARET", " CAROUSEL", " CATS", " CHICAGO"],
      },
      {
        category: "CLEANING VERBS",
        words: ["DUST", " MOP", " SWEEP", " VACUUM"],
      },
      {
        category: "___ MAN SUPERHEROES",
        words: ["BAT", " IRON", " SPIDER", " SUPER"],
      },
    ],
    allWords: [
      "ADIDAS",
      " NIKE",
      " PUMA",
      " REEBOK",
      "CABARET",
      " CAROUSEL",
      " CATS",
      " CHICAGO",
      "DUST",
      " MOP",
      " SWEEP",
      " VACUUM",
      "BAT",
      " IRON",
      " SPIDER",
      " SUPER",
    ],
  },
  {
    solutions: [
      {
        category: "FACIAL FEATURES",
        words: ["CHEEK", " EYE", " MOUTH", " NOSE"],
      },
      {
        category: "SYNONYMS FOR EAT",
        words: ["CHOW", " GOBBLE", " SCARF", " WOLF"],
      },
      {
        category: "DOG BREEDS, INFORMALLY",
        words: ["LAB", " PEKE", " PIT", " POM"],
      },
      {
        category: "MEMBERS OF A TRIO",
        words: ["AMIGO", " KING", " STOOGE", " TENOR"],
      },
    ],
    allWords: [
      "CHEEK",
      " EYE",
      " MOUTH",
      " NOSE",
      "CHOW",
      " GOBBLE",
      " SCARF",
      " WOLF",
      "LAB",
      " PEKE",
      " PIT",
      " POM",
      "AMIGO",
      " KING",
      " STOOGE",
      " TENOR",
    ],
  },
  {
    solutions: [
      {
        category: "FOOTWEAR",
        words: ["BOOT", " LOAFER", " PUMP", " SNEAKER"],
      },
      {
        category: "UNITS OF LENGTH",
        words: ["FOOT", " LEAGUE", " MILE", " YARD"],
      },
      {
        category: "MAGAZINES",
        words: ["ESSENCE", " PEOPLE", " TIME", " US"],
      },
      {
        category: "LETTER HOMOPHONES",
        words: ["ARE", " QUEUE", " SEA", " WHY"],
      },
    ],
    allWords: [
      "BOOT",
      " LOAFER",
      " PUMP",
      " SNEAKER",
      "FOOT",
      " LEAGUE",
      " MILE",
      " YARD",
      "ESSENCE",
      " PEOPLE",
      " TIME",
      " US",
      "ARE",
      " QUEUE",
      " SEA",
      " WHY",
    ],
  },
  {
    solutions: [
      {
        category: "WET WEATHER",
        words: ["HAIL", " RAIN", " SLEET", " SNOW"],
      },
      {
        category: "NBA TEAMS",
        words: ["BUCKS", " HEAT", " JAZZ", " NETS"],
      },
      {
        category: "KEYBOARD KEYS",
        words: ["OPTION", " RETURN", " SHIFT", " TAB"],
      },
      {
        category: "PALINDROMES",
        words: ["KAYAK", " LEVEL", " MOM", " RACE CAR"],
      },
    ],
    allWords: [
      "HAIL",
      " RAIN",
      " SLEET",
      " SNOW",
      "BUCKS",
      " HEAT",
      " JAZZ",
      " NETS",
      "OPTION",
      " RETURN",
      " SHIFT",
      " TAB",
      "KAYAK",
      " LEVEL",
      " MOM",
      " RACE CAR",
    ],
  },
];
